In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
rating_data = pd.read_csv("rating_complete.csv")
anima_data = pd.read_csv("anime.csv")

anima_data = anima_data.rename(columns={"MAL_ID": "anime_id"})
anima_contact_data = anima_data[["anime_id", "Name"]]

In [3]:
rating_data = rating_data.merge(anima_contact_data, left_on = 'anime_id', right_on = 'anime_id', how = 'left')
rating_data = rating_data[["user_id", "Name", "anime_id","rating"]]
rating_data.head(20)

    user_id                                             Name  anime_id  rating
0         0  Fullmetal Alchemist: The Conqueror of Shamballa       430       9
1         0                         Kanojo to Kanojo no Neko      1004       5
2         0                                   Kaiketsu Zorro      3010       7
3         0                                          Jin-Rou       570       7
4         0                                   Igano Kabamaru      2762       9
5         0                              Howl no Ugoku Shiro       431       8
6         0                                   Hotaru no Haka       578      10
7         0                 Kumo no Mukou, Yakusoku no Basho       433       6
8         0                                       Ghost Hunt      1571      10
9         0                              Fullmetal Alchemist       121       9
10        0                                  Fate/stay night       356       9
11        0                                  Erementar Gerad      1250       7
12        0          Daisougen no Chiisana Tenshi: Bush Baby      2913       6
13        0                            Byousoku 5 Centimeter      1689       6
14        0                                   Black Cat (TV)        68       6
15        0                                        Ged Senki      1829       7
16        0                                    Legend of Duo       600       6
17        0                          Jungle no Ouja Taa-chan      3418       9
18        0                                    Mononoke Hime       164       8
19        0                     Yu☆Gi☆Oh!: Hikari no Pyramid      1894       7

In [4]:
count = rating_data['user_id'].value_counts()
count1 = rating_data['anime_id'].value_counts()
# rating_data = rating_data[rating_data['user_id'].isin(count[count >= 500].index)].copy()
# rating_data = rating_data[rating_data['anime_id'].isin(count1[count1 >= 100].index)].copy()
rating_data.shape

(18915412, 4)

In [5]:
user_ids = rating_data["user_id"].unique().tolist()
user2user_encoded = {x: i for i, x in enumerate(user_ids)}
user_encoded2user = {i: x for i, x in enumerate(user_ids)}
rating_data["user"] = rating_data["user_id"].map(user2user_encoded)
n_users = len(user2user_encoded)

anime_ids = rating_data["anime_id"].unique().tolist()
anime2anime_encoded = {x: i for i, x in enumerate(anime_ids)}
anime_encoded2anime = {i: x for i, x in enumerate(anime_ids)}
rating_data["anime"] = rating_data["anime_id"].map(anime2anime_encoded)
n_animes = len(anime2anime_encoded)

print("Num of users: {}, Num of animes: {}".format(n_users, n_animes))
print("Min total rating: {}, Max total rating: {}".format(min(rating_data['rating']), max(rating_data['rating'])))

Num of users: 23004, Num of animes: 10510
Min total rating: 1, Max total rating: 10

In [6]:
piviot_table = rating_data.pivot_table(index=["anime_id"],columns="user_id", values="rating").fillna(0)
piviot_table

user_id,17,19,42,111,112,146,156,172,198,222,...,353300,353304,353311,353318,353325,353326,353328,353365,353395,353398
anime_id,,,,,,,,,,,,,,,,,,,,,
1,0.0,8.0,0.0,0.0,10.0,0.0,9.0,9.0,0.0,9.0,...,10.0,7.0,0.0,0.0,9.0,0.0,9.0,0.0,10.0,0.0
5,0.0,6.0,0.0,0.0,9.0,0.0,8.0,8.0,0.0,7.0,...,9.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,8.0,0.0
6,0.0,8.0,0.0,9.0,0.0,0.0,8.0,4.0,0.0,0.0,...,8.0,7.0,0.0,0.0,8.0,0.0,0.0,0.0,9.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47307,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47398,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47402,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47616,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48456,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
from scipy.sparse import csr_matrix
piviot_table_matrix = csr_matrix(piviot_table.values)

In [8]:
from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(metric="cosine", algorithm="brute")
model.fit(piviot_table_matrix)

NearestNeighbors(algorithm='brute', metric='cosine')

In [9]:
def predict(anime_id):
    
    query = piviot_table.iloc[anime_id, :].values.reshape(1, -1)
    distance, suggestions = model.kneighbors(query, n_neighbors=6)
    
    for i in range(0, len(distance.flatten())):
        if i == 0:
            print('Recommendations for {0}:\n'.format(piviot_table.index[anime_id]))
        else:
            print('{0}: {1}, with distance of {2}:'.format(i, piviot_table.index[suggestions.flatten()[i]], distance.flatten()[i]))

Recommendations for 32:

1: 30, with distance of 0.1315257090186338:
2: 2759, with distance of 0.23816894322325988:
3: 3784, with distance of 0.25583499983407476:
4: 31, with distance of 0.28800894630950946:
5: 3785, with distance of 0.31208835623116515: